### PR TITLE
Single search Field update

### PR DESCRIPTION
**Pull request by ViceSyndicate**
This request removes 2 search fields.

It also removes the ability to search for SPECIFIC results where for example Red Ford
is entered then only Red Fords show up as a result.

If we merge this request then We would get ALL Fords and ALL Red vehicles.

Up to you guys to decide what we should keep.

### CODE REVIEW

**Comment by SallyResch** [comment]
Think it looks good. I vote to merge it

**Review by SallyResch — APPROVED** [review]
Think it looks good, I vote merge

**Review by Annisson — APPROVED** [review]
Looks good

**Comment by ViceSyndicate** [comment]
We're going with Emrets more specified search solution.

**Pull request closed without merging**
